import { Router } from "express";
import { authRoutes } from "./auth.routes.js";
import { publicRoutes } from "./public.routes.js";
import { dashboardRoutes } from "./dashboard.routes.js";
import { attendanceRoutes } from "./attendance.routes.js";
import { clientRoutes } from "./client.routes.js";
import { roomRoutes } from "./room.routes.js";
import { reservationRoutes } from "./reservation.routes.js";
import { checkInRoutes, checkOutRoutes } from "./reception.routes.js";
import { clientPortalRoutes } from "./client-portal.routes.js";
import { createOrderRoutes } from "./order.routes.js";
import { poolRoutes } from "./pool.routes.js";
import { cleaningRoutes } from "./cleaning.routes.js";
import { eventRoutes } from "./event.routes.js";
import { inventoryRoutes, productRoutes } from "./inventory.routes.js";
import { productionRoutes } from "./production.routes.js";
import { recipeRoutes } from "./recipe.routes.js";
import { reportRoutes } from "./report.routes.js";
import { supplyRequestRoutes } from "./supply-request.routes.js";
import { createBasicRoutes } from "./basic.routes.js";
import { cashRoutes, invoiceRoutes, parkingRoutes, paymentRoutes, purchaseRoutes, roleRoutes, settingRoutes, supplierRoutes, userRoutes } from "./admin.routes.js";
import { prisma } from "../config/prisma.js";

export const apiRoutes = Router();

apiRoutes.get("/health", async (req, res) => {
  try {
    await prisma.$queryRaw`SELECT 1`;
    res.json({ status: "ok", database: "connected" });
  } catch (error) {
    res.status(503).json({ status: "error", database: "disconnected" });
  }
});
apiRoutes.use("/public", publicRoutes);
apiRoutes.use("/attendance", attendanceRoutes);
apiRoutes.use("/asistencia", attendanceRoutes);
apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/dashboard", dashboardRoutes);
apiRoutes.use("/clients", clientRoutes);
apiRoutes.use("/clientes", clientRoutes);
apiRoutes.use("/client", clientPortalRoutes);
apiRoutes.use("/rooms", roomRoutes);
apiRoutes.use("/habitaciones", roomRoutes);
apiRoutes.use("/reservations", reservationRoutes);
apiRoutes.use("/reservas", reservationRoutes);
apiRoutes.use("/checkin", checkInRoutes);
apiRoutes.use("/checkout", checkOutRoutes);
apiRoutes.use("/orders", createOrderRoutes("PEDIDOS"));
apiRoutes.use("/restaurant", createOrderRoutes("RESTAURANTE", "RESTAURANTE"));
apiRoutes.use("/restaurante", createOrderRoutes("RESTAURANTE", "RESTAURANTE"));
apiRoutes.use("/bar", createOrderRoutes("BARTENDER", "BARTENDER"));
apiRoutes.use("/bartender", createOrderRoutes("BARTENDER", "BARTENDER"));
apiRoutes.use("/pool", poolRoutes);
apiRoutes.use("/piscina", poolRoutes);
apiRoutes.use("/events", eventRoutes);
apiRoutes.use("/eventos", eventRoutes);
apiRoutes.use("/parking", parkingRoutes);
apiRoutes.use("/cochera", parkingRoutes);
apiRoutes.use("/cleaning", cleaningRoutes);
apiRoutes.use("/limpieza", cleaningRoutes);
apiRoutes.use("/products", productRoutes);
apiRoutes.use("/inventory", inventoryRoutes);
apiRoutes.use("/inventario", inventoryRoutes);
apiRoutes.use("/production", productionRoutes);
apiRoutes.use("/produccion", productionRoutes);
apiRoutes.use("/recipes", recipeRoutes);
apiRoutes.use("/recetas", recipeRoutes);
apiRoutes.use("/supply-requests", supplyRequestRoutes);
apiRoutes.use("/solicitudes-insumos", supplyRequestRoutes);
apiRoutes.use("/purchases", purchaseRoutes);
apiRoutes.use("/compras", purchaseRoutes);
apiRoutes.use("/suppliers", supplierRoutes);
apiRoutes.use("/proveedores", supplierRoutes);
apiRoutes.use("/payments", paymentRoutes);
apiRoutes.use("/pagos", paymentRoutes);
apiRoutes.use("/invoices", invoiceRoutes);
apiRoutes.use("/facturacion", invoiceRoutes);
apiRoutes.use("/cash", cashRoutes);
apiRoutes.use("/caja", cashRoutes);
apiRoutes.use("/users", userRoutes);
apiRoutes.use("/usuarios", userRoutes);
apiRoutes.use("/roles", roleRoutes);
apiRoutes.use("/reports", reportRoutes);
apiRoutes.use("/reportes", reportRoutes);
apiRoutes.use("/audit", createBasicRoutes("audit", "AUDITORIA", { user: true }));
apiRoutes.use("/auditoria", createBasicRoutes("audit", "AUDITORIA", { user: true }));
apiRoutes.use("/settings", settingRoutes);
apiRoutes.use("/configuracion", settingRoutes);
